name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  silverstripe-api:
    name: silverstripe-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - run: composer validate --no-check-publish
      - name: PHP syntax check
        run: find src -name '*.php' -print0 | xargs -0 php -l
