name: Modules PR Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  silverstripe-api:
    name: silverstripe-api
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/silverstripe-api
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - run: composer validate --no-check-publish

  react-sdk:
    name: react-sdk
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/react-sdk
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/react-sdk/package-lock.json
      - run: npm ci
      - run: npm run build

  react-native-sdk:
    name: react-native-sdk
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/react-native-sdk
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: packages/react-native-sdk/package-lock.json
      - run: npm ci
      - run: npm run build
